### ISSUE TITLE
Debounce so that there's only one pending promise

### ISSUE THREAD

**Issue by fregante** [sindresorhus/promise-fun#15]
```js
async function action() {
	delay(3000);
	alert('Done')!
}

button.onclick = action;
```

If the user double-clicks the button, `action` is run twice. This usually debounced/throttled with timeouts, but how would you throttle this so that `action` calls don't pile up instead?

This is different from `p-debounce` since that's timeout-based and completely ignores the state of the promise.

**Comment by Richienb** [comment]
I'm assuming you want to execute a promise-returning function unless it is already running.

Since I can't add a module, here's how it would work:

```js
const pStateThrottle = async function_ => {
	let isRunning = false

	return (...arguments_) => {
		if (!isRunning) {
			isRunning = true
			await function_(...arguments_)
			isRunning = false
		}
	}
}

const action = pStateThrottle(async () => {
	await delay(3000)
	alert("Waited 3 seconds")
})

button.onclick = action
```

**Comment by fregante** [comment]
Looks good. I'd use try/finally to return the value and ensure that the state is always updated

```js
		try {
			isRunning = true
			return await function_(…arguments_)
		} finally {
			isRunning = false
		}
```

**Comment by sindresorhus** [comment]
I wonder if this could be an option or separate method to https://github.com/sindresorhus/p-debounce

**Comment by sindresorhus** [comment]
Alternative names:

- `p-dedupe`
- `p-deduplicate`
- `p-ensure-one`

**Comment by sindresorhus** [comment]
Just nitpick, I would make it return early:

```js
const pStateThrottle = async function_ => {
	let isRunning = false

	return (...arguments_) => {
		if (isRunning) {
			return
		}

		try {
			isRunning = true
			return await function_(…arguments_)
		} finally {
			isRunning = false
		}
	}
}

const action = pStateThrottle(async () => {
	await delay(3000)
	alert("Waited 3 seconds")
})

button.onclick = action
```

**Comment by sindresorhus** [comment]
Currently, when called a second time, it will just resolve the promise right away. That's fine for this specific use-case, but I think it might be better to store the promise and return that instead. That way the second call would wait for the original delay to finish too.

**Comment by Richienb** [comment]
> I think it might be better to store the promise and return that instead. 

```js
const pStateThrottle = async function_ => {
	let isRunning = false
	let currentPromise

	return (...arguments_) => {
		if (isRunning) {
			return currentPromise
		}

		try {
			isRunning = true
			currentPromise = function_(…arguments_)
			return await currentPromise
		} finally {
			isRunning = false
		}
	}
}

const action = pStateThrottle(async () => {
	await delay(3000)
	alert("Waited 3 seconds")
})

button.onclick = action
```

**Comment by sindresorhus** [comment]
@Richienb You don't need the boolean then.

**Comment by fregante** [comment]
> I wonder if this could be an option or separate method to [sindresorhus/p-debounce](https://github.com/sindresorhus/p-debounce)

Only if it's an _alternative_ to the timer rather than an addition (i.e. just "wait for the promise", never "wait for the promise _and_ the timer")

Given that none of the options apply to this behavior, the signature can become:

```js
function debounce(fn, [wait, [options]])
```

No `wait` means it just waits for the Promise.

**Comment by sindresorhus** [comment]
@fregante Or a separate method? `debounce.single`/`debounce.wait`/`debounce.one`.

Also, related issue: https://github.com/sindresorhus/p-debounce/issues/3

**Comment by fregante** [comment]
`debounce.promise` would make the most sense to me

**Comment by Richienb** [comment]
Debouncing queues extra calls to be run after a delay whereas throttling dumps extra calls without ever executing them. We are actually debouncing function calls.

**Comment by fregante** [comment]
> Debouncing queues extra calls to be run after a delay

No, debouncing does not queue calls. Only `p-debounce` returns the same promise for all the calls, but usually debouncers **drop** calls. In fact they're often used to in event listeners like `window.onresize = debounce(callback, 300)` so that they're only called once the resize events stop.

Throttling calls the function "at most every X milliseconds", so I don't think it applies here.

**Comment by fregante** [comment]
Therefore, this should result in one `alert`:

```js
const action = debounce.promise(async () => {
	delay(3000);
	alert('Done')!
})

action();
action();
```

**Comment by Richienb** [comment]
I've begun implementing this in `p-debounce` and I've come to this realisation: What is this supposed to do?

```js
const action = debounce.promise(async value => {
	delay(3000);
	return value
})

action("a");
action("b");
```

Right now, it throws away `"b"` which leads to unpredictable results as the second call will resolve with `b`.

Do we want to queue up calls instead of discarding them in a separate implementation in `p-throttle`?

**Comment by fregante** [comment]
> Right now, it throws away `"b"` which leads to unpredictable results as the second call will resolve with `a`.

That's what `debounce` does, it discards calls:

https://github.com/sindresorhus/p-debounce/blob/46ed3aab5974c2ced01a166233965bfa129de9ce/test.js#L49-L50

**Comment by Richienb** [comment]
> Throttle discards calls too. You're thinking of queues, which neither `debounce` nor `throttle` are.

`p-throttle` defines `queue`:

https://github.com/sindresorhus/p-throttle/blob/004bcd3d837bc24ca55a88f8c4c8896a95545c91/index.js#L19

**Comment by fregante** [comment]
Indeed.

[<img width="100" src="https://i.kym-cdn.com/photos/images/original/001/206/584/f21.jpg">](https://knowyourmeme.com/photos/1206584-webcomics)

How's `p-throttle` different from [p-limit](https://github.com/sindresorhus/p-limit)? It appears the same down to the concurrency option. 

`p-throttle` is the only "throttle" module that behaves this way. See this example, none of them execute the calls 2, and 3 except p-throttle.

https://runkit.com/bfred-it/5ffe7a7977172c001b32528f

**Comment by sindresorhus** [comment]
> p-throttle is the only "throttle" module that behaves this way. See this example, none of them execute the calls 2, and 3 except p-throttle.

Yeah, I don't remember why I made it like that. Seems you're not the only confused one: https://github.com/sindresorhus/p-throttle/issues/15 Maybe we should add a `discard` option and make it default to `true`? That way the default behavior is the expected one and users can set it to `false` to get the old behavior.

**Comment by Richienb** [comment]
Since this new function also discards calls, does it still make sense for it to be added to `p-debounce`?

**Comment by fregante** [comment]
> Yeah, I don't remember why I made it like that

If I think about it it _does_ make sense as it does _throttle_ calls; the only issue is that it doesn't match the meaning `throttle` has in the JS community. 


> How's `p-throttle` different from [p-limit](https://github.com/sindresorhus/p-limit)?

Answering myself: `p-limit` doesn't have an `interval` parameter

**Comment by fregante** [comment]
I think this should/could be part of `p-memoize`:

- it supports multiple calls at once, as long as the parameters are different
- **can** support "one call at once regardless of parameters" by just passing `cacheKey: () => {}` probably

Implementation-wise it would be identical to how `cachePromiseRejection` is implemented:

```js
if (!cachePromiseResolution && cacheItem && cacheItem.then) {
	  cacheItem.then(() => {
		  cache.delete(cacheKey(arguments_));
	  });
}
```

**Comment by etienne-martin** [comment]
> Alternative names:
> 
> * `p-dedupe`
> * `p-deduplicate`
> * `p-ensure-one`

I suggest the name `p-collapse`, as the behavior is similar to request collapsing on CDNs.

Request collapsing is the practice of combining multiple requests for the same object into a single request to origin, and then using the resulting response to satisfy all pending requests.

**Comment by fregante** [comment]
Closing in favor of https://github.com/sindresorhus/p-memoize/issues/20

**Comment by TehShrike** [comment]
@fregante you may be interested in https://github.com/TehShrike/gate-keeper
