### ISSUE TITLE
Add caolan/async

### ISSUE THREAD

**Issue by kibiz0r** [sindresorhus/promise-fun#16]
I'm kinda surprised this isn't on here yet: https://caolan.github.io/async/v3/

It's basically the async equivalent of lodash.

**Comment by Richienb** [comment]
This isn't an awesome list - only first party Sindre Sorhus modules are
added here.
[image: avatar]
Richie Bendall
Website: https://richienb.github.io
Email: ***@***.***
[image: social-icon-github] <https://github.com/Richienb> [image:
social-icon-youtube] <https://youtube.com/RichieBendall> [image:
social-icon-stackoverflow]
<https://stackoverflow.com/users/8384910/richie-bendall>

**Comment by kibiz0r** [comment]
Whoops, my bad. Sorry about that. 🤭
