### ISSUE TITLE
p-map for a function or p-whilst with concurrency

### ISSUE THREAD

**Issue by gsouf** [sindresorhus/promise-fun#17]
Hi,

Is there any package here that works like p-map but with a function instead of an array? Or like p-whislt with concurency.

Something that takes a function returning a promise or null. As long as the function returns a promise then it keeps going with concurency managed.

Like this package https://www.npmjs.com/package/es6-promise-pool

Thanks

**Comment by sindresorhus** [comment]
Nothing exactly like that, but you can achieve it with https://github.com/sindresorhus/p-limit

**Comment by gsouf** [comment]
Thanks, p-limit does not seem to be what I'm looking for, I'll do some wrapper around p-queue.
