### ISSUE TITLE
Run async function return values

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/promise-fun#18]
An array of async functions that are called at the same time with each returning async functions that are run in order. Useful for executing a list of tasks where you have to do some preparation before each one that can be done without doing the actual task. For example:

```js
await pAsyncLoadedTasks([
	async () => {
		const converted = await convertPart(foo)
		return async () => play(converted)
	},
	async () => {
		const converted = await convertPart(bar)
		return async () => play(converted)
	}
])
```

In this case, the first async function is executed and the function it returns is executed whilst the second async function is executed and then its returned function is executed after.

Maybe like this?

```js
import pMap from "p-map"
import PQueue from "p-queue"

const pAsyncLoadedTasks = async (jobs, options) => {
	const returnValues = []

	const queue = new PQueue({ concurrency: 1 })

	await pMap(jobs, async createJob => {
		const job = await createJob()

		queue.add(async () => {
			returnValues.add(await job)
		})
	}, options)

	await queue.onEmpty()

	return returnValues
}
```

**Comment by sindresorhus** [comment]
Seems like you could easily solve this with `p-all` or just simply a `for-of` loop.

```js
const pAsyncLoadedTasks = tasks => pAll(tasks.map(task => task()), {concurrency: 1}));
```

**Comment by Richienb** [comment]
The thing is, `task` also returns an async function which resolves with another async function that pAll needs to execute so `.map` doesn't work here.

**Comment by sindresorhus** [comment]
Right. If you replace `p-all` with `p-map` it should work though. I forgot that p-all doesn't accept promises.

**Comment by Richienb** [comment]
That doesn't fix the problem. The goal is to start with an array of asynchronous functions and to run them all at the same time. Each one would then return their own asynchronous function that needs to be executed in order whilst the other functions from the original array are still running.

**Comment by sindresorhus** [comment]
Seems to work for me:

```js
import pMap from 'p-map';
import delay from 'delay';

const pAsyncLoadedTasks = tasks => pMap(tasks.map(task => task()), x => x(), {concurrency: 1});

(async () => {
	await pAsyncLoadedTasks([
		async () => {
			await delay(11);
			console.log('foo');

			return async () => {
				await delay(20);

				console.log('foo2');
			}
		},
		async () => {
			await delay(10);
			console.log('bar');

			return async () => {
				console.log('bar2');
			}
		}
	]);
})();
```

**Comment by Richienb** [comment]
So it does. Nice!
