### ISSUE TITLE
Move .then/.catch-based modules to their own section

### ISSUE THREAD

**Issue by fregante** [sindresorhus/promise-fun#19]
Modules like `p-log` and `p-tap` don't fit the "avoid .then" suggestion, so they aren't as useful anymore.

What do you think about moving them to their own "old-style modules" section or something like that? With dozens of packages these IMHO are just clutter among packages are still useful.

They were even just updated for Node 12 support but their examples still have then/catch: https://github.com/sindresorhus/p-log

**Comment by sindresorhus** [comment]
I agree.
