### ISSUE TITLE
publish this?

### ISSUE THREAD

**Issue by mmkal** [sindresorhus/promise-fun#25]
What do you think about publishing this as an npm package? Could be useful in environments where install size isn't an issue and/or where tree shaking is enough to not worry about bloat. Being able to switch between them with worrying about installing/uninstalling would be useful. Esp. since it's not always 100% clear which one will be needed when you start experimenting. I often _want_ to switch from p-all, to p-map, to p-props, to p-throttle etc., and every switch is a bit painful.

Usage:

```
npm install p-suite
```

```ts
import pMemoize from 'p-suite/p-memoize'
import pAll from 'p-suite/p-all'
```

Note I used `p-suite` above because someone did more or less this using `promise-fun` but it's 7 years old.

**Comment by sindresorhus** [comment]
This is a non-goal for this project. It's also not something I want to maintain.
