### ISSUE TITLE
[Question] - Is there a p-* lib that can queue a number of promises for a given interval, and then dequeue them in batches?

### ISSUE THREAD

**Issue by JQuezada0** [sindresorhus/promise-fun#27]
Basically what the title says. I see many ways to hold promises given some condition/time, but I'm wondering if there's any way to get the total promises that were queued as a batch? If not, I think it should be possible to use `p-queue` to dequeue the amount of times equal to the size of the queue.

**Comment by JQuezada0** [comment]
Nevermind, I was able to get the batch-processing behavior I was looking for by holding onto an array of things to be processed, and then using `p-queue` to force sequential ordering of an async function that drains the array and processes in batch. The async function that does the processing uses a delay to give some time for the array to fill up, and will no-op if the array is empty.

**Comment by SimenB** [comment]
@JQuezada0 mind sharing the implementation? 🙂 Some sort of `p-batch` or whatever makes sense to me as a general utility (like a minimal [`dataloader`](https://www.npmjs.com/package/dataloader) without caching)
